### ISSUE TITLE
[CSS] Text is unstyled

### ISSUE THREAD

**Issue by runxel** [cdriesler/nodepen#65]
Please be aware that most text on the website is currently unstyled.
This means, that the fallback _might_ be black, but not necessarily has to:

![grafik](https://user-images.githubusercontent.com/2277182/117625090-f125ac00-b175-11eb-9c01-2db3d88f870f.png)

**Comment by cdriesler** [comment]
Interesting, totally flew under the radar. Thank you for the catch.

Do you know how I can test/confirm I've fixed this correctly (i.e. do you know where the grey fallback color is coming from, in your case?)

**Comment by runxel** [comment]
Don't worry, that's an easy "mistake".
The grey color comes from my custom theme.
I inverted the default colors, so if there is no styling present it will make the background dark (instead of white) and any unstyled text light (instead of black).
(Which is kinda nice for reading mailings lists online e.g.)
But... to be honest this of course is a rather special case and I doubt that many people are aware of having unstyled things on their webpages.

I'm not sure if there is any nice auto-test for this. 🤔
But if you never do any `color: unset;` and just have a `body {color: #000;}` everything should be fine.
To be sure you could do a `color: inherit;`, but I doubt its truly necessary.
