### ISSUE TITLE
Clicking component menu shouldn't places component underneath mouse event

### ISSUE THREAD

**Issue by ianjanicki** [cdriesler/nodepen#68]
Clicking on component from menu should add component to center of window, or some other accessible method.

![Screen Shot 2021-05-12 at 4 59 00 PM](https://user-images.githubusercontent.com/4295837/118049496-71e5d300-b343-11eb-8d4f-b88a75b6a51b.png)

**Comment by cdriesler** [comment]
Hard agree. Currently re-imagining this part for touch screens, will keep this top of mind.
