### ISSUE TITLE
alternate wire and graph paradigms

### ISSUE THREAD

**Issue by cdriesler** [cdriesler/nodepen#76]
[via tweet](https://twitter.com/jmanooch/status/1420077081879359488?s=20)

Set out to emulate the look and feel of grasshopper on nodepen, but we also have a chance to reconsider some of its choices. Explicit History was first released in 2007!

Will keep developing thoughts and references here.

**Comment by jmanooch** [comment]
Happy to add any comments and references I can.

**Comment by cdriesler** [comment]
Any time! There's no "NodePen forum" so this is as good a place as any. ty in advance, will also keep an eye out

**Comment by cdriesler** [comment]
Moved to https://github.com/cdriesler/nodepen/discussions/85
